name: fyp1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  pin_code_fields: ^8.0.1
  day_night_time_picker: ^1.3.0+1
  intl: ^0.18.1
  analog_clock: ^0.1.1
  camera: ^0.10.5+5
  google_maps_flutter: ^2.5.0
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  time_duration_picker: ^0.0.1
  progressive_time_picker: ^0.0.9
  time_picker_spinner: ^0.0.1
  custom_sliding_segmented_control: ^1.8.1
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  dio: ^5.4.0
  supabase_flutter: ^2.2.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

